### ISSUE TITLE
Missing model.json and traner.json file for tf_mg branch

### ISSUE THREAD

**Issue by saikia1** [kevinid/molecule_generator#1]
Unable to find `model.json` and `trainer.json` files for tensorflow mg branch.

**Comment by odek53r** [comment]
Both of model.json and trainer.json are configuration files. 
I try to find out the parameters used in this work and recreate ones.

model.json file looks like as the following.
`{"n_node_types":33,
"n_edge_types":4,
"n_d":2,
"Fe":16,
"Fh":[32, 64, 128, 128, 256, 256],
"Fskip":256,
"Fh_policy":128,
"learning_rate":0.001,
"decay_step":100,
"decay_rate":0.001,
"beta1":0.9,
"beta2":0.999,
"epsilon":0.00000001,
"clip_val":3.0,
"activation":"relu",
"batch_norm":true
}`

trainer.json file looks like as the following.
`{"dataset":{
			"file_name":"datasets/ChEMBL.txt",
			"num_epoch":50000,
			"generator":"from_smiles_to_batch",
			"batch_size":25,
			"num_pool":null,
			"kwargs":{"queue_in_size":10,
					"queue_out_size":10,
					"k":10,
					"p":0.9,
					"conditional":false,
					"is_train":true},
			"sampler":null
			},
"model_name":"graph_lm",
"summarize_step":10
}`
