### ISSUE TITLE
running errors

### ISSUE THREAD

**Issue by xuzhang5788** [kevinid/molecule_generator#2]
I run exmples.ipynb, but received error message like this
No module named 'utils'

I found file utils.py at /data/ folder. Can you tell me why?
I am using python 3.5

Thanks

**Comment by odek53r** [comment]
This work is built using Python 2.7. Maybe you can try it with Python 2.7.

**Comment by xuzhang5788** [comment]
@odek53r 
I used $2to3 -w ***.py command to transfer your Python2 files into Python3 files, Then it works now. Thank you.
